name: Dissect CI
on: [push, pull_request, workflow_dispatch]

jobs:
  ci:
    uses: fox-it/dissect-workflow-templates/.github/workflows/dissect-ci-template.yml@DIS-2016_remove-iodc-from-publishing
    with:
      run_tests: false
      run_linting: false
    secrets: inherit
  publish:
    if: ${{ github.ref_name == 'main' || github.ref_type == 'tag' }}
    needs: [ci]
    runs-on: ubuntu-latest
    environment: dissect_publish
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: packages
          path: dist/
      # According to the documentation, it automatically looks inside the `dist/` folder for packages.
      - name: Publish package distributions to Pypi
        uses: pypa/gh-action-pypi-publish@release/v1
